#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Simpl >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Simpl=/luci-static/simpl
		set luci.main.mediaurlbase=/luci-static/simpl
		commit luci
	EOF
fi

exit 0
